name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Criterion
        run: sudo apt update && sudo apt install -y libcriterion-dev

      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Format checking
        run: ./clang-format check
          
      - name: Build
        run: make

      - name: Tests
        run: make check
        
      - name: Cleaning 
        run: make clean

      - name: docs 
        run: doxygen Doxyfile
